<?php
/**
 * Media optimization class
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

class Jay_Core_Media {

	/**
	 * Constructor
	 */
	public function __construct() {
		add_action( 'after_setup_theme', array( $this, 'add_custom_image_sizes' ) );
		add_filter( 'intermediate_image_sizes_advanced', array( $this, 'limit_image_sizes' ) );
        add_filter( 'big_image_size_threshold', array( $this, 'disable_big_image_threshold' ) );
	}

	/**
	 * Add custom image size for Jay Core
	 */
	public function add_custom_image_sizes() {
        // Check if feature is enabled
        if ( ! get_field( 'jay_core_optimize_media', 'option' ) ) {
            return;
        }

		add_image_size( 'jay_core_thumb', 600, 400, true );
	}

	/**
	 * Limit image sizes generated by WordPress
	 */
	public function limit_image_sizes( $sizes ) {
        // Check if feature is enabled
        if ( ! get_field( 'jay_core_optimize_media', 'option' ) ) {
            return $sizes;
        }

		$allowed_sizes = array( 'thumbnail', 'jay_core_thumb' );

		foreach ( $sizes as $size_name => $size_data ) {
			if ( ! in_array( $size_name, $allowed_sizes ) ) {
				unset( $sizes[ $size_name ] );
			}
		}

		return $sizes;
	}

    /**
     * Disable big image threshold to prevent generating additional scaled images if needed
     */
    public function disable_big_image_threshold( $threshold ) {
        if ( get_field( 'jay_core_optimize_media', 'option' ) ) {
            return false;
        }
        return $threshold;
    }
}
